name: 'ecommerce_dbt'
version: '1.0.0'
config-version: 2

profile: 'ecommerce_dbt'

log-path: /tmp/dbt_logs
packages-install-path: /tmp/dbt_packages

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  ecommerce_dbt:

    bronze:
      +schema: bronze
      +materialized: incremental
      +tags: ["bronze"]

    silver:
      +schema: silver
      +materialized: incremental
      +tags: ["silver"]

    gold:
      +schema: gold
      +materialized: table
      +tags: ["gold"]
